### Get all parlimen sessions (as of 2026 Jan, 15 sessions)
GET https://www.parlimen.gov.my/hansard-dewan-negara.html?uweb=dn&arkib=yes&ajx=1&id=0

### Get 15th parlimen
GET https://www.parlimen.gov.my/hansard-dewan-negara.html?uweb=dn&arkib=yes&ajx=1&id=0_15

### Get 15th parlimen, penggal ketiga
GET https://www.parlimen.gov.my/hansard-dewan-negara.html?uweb=dn&arkib=yes&ajx=1&id=0_15_3

### Get 15th parlimen, penggal ketiga, mesyuarat ke-2, download pdf
GET https://www.parlimen.gov.my/hansard-dewan-negara.html?uweb=dn&arkib=yes&ajx=1&id=0_15_3_2

### Download file
GET https://www.parlimen.gov.my/files/hindex/pdf/DN-23072024.pdf
