NON_SPEAKER_VERBS = [
    "reported", "resolved", "considered", "ordered", "amended", "adopted", "debated", "passed", "read", 
    "proposed", "moved", "seconded", "agreed", "adjourned", "appeal", "bill", "quote", "declare", "reads", 
    "follows", "proposal", "kata", "seperti", "berikut", "menyatakan", "memutuskan", "mempertimbangkan", 
    "mengusulkan", "mengajukan", "mengadopsi", "membahas", "melanjutkan", "menyetujui", "menolak", "mengutip", 
    "mengumumkan", "sebarang", "iaitu", "adalah", "berhajat", "berbunyi", "bagi", "bahawa", "terdapat", "sebab", "tendency",
    "irony", "ialah", "berkata", "mengatakan", "menjelaskan", "menegaskan", "mengungkapkan", "menyampaikan", "memperjelas", "mempertegas", "mempertebal",
    "report", "resolve", "consider", "order", "amend", "adopt", "debate", "pass",
    "antara", "dengan", "untuk", "sebagai", "sehingga", "karena", "sampai", "selama", "ketika", "waktu", "sebelum", "sesudah", "selanjutnya", "kemudian", "setelah", "sebelumnya", "berlangsung", "langsung",
    "menchadangkan", "sumpah", "berikrar", "berjanji", "mengikrarkan", "criticism", "election", "Opposition", "Perkhidmatan", "Akitek", "bahagian", "tahan", "composition",
    "Pemandu", "atau", "Bursary", "Biasiswa", "Kerajaan", "Kerajaan Persekutuan", "Kerajaan Negeri", "Kerajaan Tempatan", "Kerajaan Pusat", "Hadiah",
    "language", "advance", "quota", "conclude", "various", "four", "contributions", "contribution", "contributed", "contributing", "contributor", "contributes", "question", "soalan", "jawapan", "pertanyaan", "menjawab",
    "statement", "important", "significant", "notable", "remarkable", "noteworthy",
    "task", "nevertheless", "however", "although", "though", "despite", "in spite of", "regardless of", "nonetheless", "notwithstanding", "even though", "while", "whereas", "issues", "deleted", "berita", "said", "occasion", "pepatah", "belongs", "berbelah-bahagi", "understanding", "understood", "understands", "understand",
    "also", "unfortunately", "fortunately", "additionally", "moreover", "furthermore", "in addition", "as well as", "besides", "what's more", "on top of that",
    "not only that", "also", "Peringatan", "Taman", "colonial", "clear", "rata", "mengikut", "Latehan", "warning", "ranchangan", "relative", "Jumlah", "further", "menurut","di-luluskan","academic", "merayu", "employed", "left", "pikul", "very", "sometimes", "units",
    "izin", "yesterday", "allegations", "Dental", "Tambahan", "lalang", "purpose", "consult", "kilang", "Pelateh", "trained", "says", "personnel", "conditions", "berjaya", "another", "jawatan","acting", "rhyme", "incorruptible", "consequence", "kesalahan", "rural",
    "mengapa", "mengambil", "tersebut", "dimainkan", "ditelitikan", "mengelirukan", "tetapi", "bertanya", "diterbitkan", "rakyat", "menandatangani",
    "pengurus", "peruntukan", "dimuliakan", "kekurangan", "bangunan-bangunan", "sekalilah", "mengelakkan", "environmental", "incidence",
    "pacific", "kenapakah", "samping", "strategi", "dilaporkan", "mencadangkan", "mengenai", "menanya", "dimanakah", "tanah",
    "menggalak", "mendahulukan", "penganiayaan", "dianjurkan", "tandatangan", "overhaul", "mengandungi", "tatatertib", "ataupun", "sure", "getting",
    "dapati", "begitu", "menjalankan", "mengadakan", "kelas", "fasal", "clause", "point", "following", "against", "difficult", "because",
    "akta", "pindaan", "perintah", "duti", "wow", "ketawa", "riuh", "sepotong", "menggunakan", "reputation", "tepuk", "disampuk", "tingkatan", "peratus", 
    "broadband", "berhenti", "bulan", "tajuk", "perkara", "mereka", "pembinaan", "quran", "Loceng", "hari ini", "ada", "masing", "Tidak", "akan", "ampun", "sopan", "sini", "apa", "apakah", "membaca", "himself", "cadangan", 
    "b", "bahasa", "baik", "bangun", "banyak", "baru", "begini", "berapa", "berbahas", "berbelanja", "daripada", "tolong", "sorak", "jelaskan", "telah", "oleh", "boleh",
    "buku","butir", "sangat", "lagi", "pervesion", "pula", "dari", "dasar", "datang", "and", "mana", "saya", "diajar", "diambil", "diberikan", "dibuat", "dimana",
    "tunjuk", "sebut", "din", "jika", "don't", "dran)", "hari", "empat", "estetika", "friend", "going", "tinggi", "kepada", "hingga", "members", "hubungan", "ibadatnya", "ini", "kalau", 
    "itu", "iuan", "jawab", "jelas", "juga", "kasih", "ke?", "kertas", "meliputi", "memohon", "kehendak", "sebelah", "dikeluarkan", "kemalangan", "bukan", "kenaikan",
    "Kepala", "ramai", "kerana", "kurang", "menunjukkan", "jangan", "laporan", "lawatan", "lebih", "lewat", "lihat", "minit", "merujuk", "macam", "maksud", "melalui", "melihat", "membalak", "membentuk", "meminta", "memperbaiki",
    "sistem", "menambah", "menarik", "membatalkan", "tadi", "memberikan", "termasuklah", "disorak", "menyeru", "merangkap", "mesti", "minat", "minta", "mungkin", "belum", "nama", "nisbah",
    "wonder", "No", "dominance", "over", "nota", "now", "number", "kilat", "nyatakan", "objektif", "down", "reach", "sum", "sebuah", "okey", "called", "this", "would", "ongoing", "opsyen", "supaya", "hendak", "orang", "ordinan", "other", "bising", 
    "overaged", "broadcasting", "anggaran", "package", "pada", "padang", "panduan", "papan", "para", "paragaf", "paragraph", "parcel", "parit", "parlimen", "parliament", "part", "pasaran", "pasifik", "pasokan", "patah", "saperti", 
    "pecahan", "pechahan", "pegawai", "pelaboran", "perbahasan", "perseorangan", "pemaliman", "pemasyhuran", "pembabitan", "kemiskinan", "pembaziran", "pembelaan", "pembelian", "pemberian", "pembuangan", "pemegang", "sempena", "penal",
    "nothing", "Div.", "Causeway", "penanggohan", "penangguhan", "pendaftar", "menengah", "dikemukakan", "Ugama", "potongan", "pengantin", "pengarang", "pengedar", "note","divided","usul","jadual", "present", "CATATAN", "CHATETAN", 
    "Contohnya", "Cuti", "text", "Diputuskan", "Erti-nya", "Ertinya", "Misalnya", "Perumahan", "Jadual", "Schedule", "terms","Umpamanya", "sejahtera", "power", "per", "rations", "penggunaan", "dikira", "English", "perlu", 
    "words", "guilty", "dialog", "additional", "again", "pihak", "lain", "alamat", "alasan", "pangkat", "answer", "Architects", "article", "these", "aturan", "average", "CATTTAN", "CHATITAN","salah", "Co.", "category", "cause", "catitan", "certificate", "change", "preferential", "chapter", "coming",
    "contoh", "currently", "there", "cycling", "division", "army", "tahun", "latinnya", "falsafahnya", "surat", "seterusnya", "dear", "deaths", "demam", "here", "he", "hanya", "ha", "huraian", "ground", "give", "gaji", "from", "firman", "priority", "aid", "finally", "fasa", "full", "canned", "Experience", "Explanation",
    "example", "ways", "total", "diputuskan", "muka", "digicam", "teachers", "concerned", "huraiannya", "come", "referred", "repeat", "quite", "some", "fruits", "approved", "written", "stated", "inflasi", "infrastruktur", "insentif", "involved", "goes", "therefore", "item", "items", "jadi", "peluru", "jual", "kajian",
    "kakitangan", "kategori", "kaum", "komen", "kriteria", "kursus", "lain", "lampu", "langkah", "lepasan", "umur", "penoh", "majlis", "anggota", "system", "fikiran", "matapelajaran", "metodologi", "many", "next", "comments", "misi", "menanam", "news", "page", "pengumuman", "puncha", "penguatkuasaan", "pentujuk", "penutup",
    "penyelesaian", "penyertaan", "penyunting", "peraturan", "percent", "perenggan", "periksaan", "peringkat", "period", "peristiwa", "pilihan", "merangkum", "status", "porah", "premium", "prioriti",
    "procedure", "progress", "promorion", "cukuplah", "qualification", "rang", "sec", "sifir", "sir", "skim", "source", "stages", "sugar","syarat", "susu", "than", "tujuan", "vital", "tak", "tarikh", "terjemahannya",
    "cara", "petang", "samalah", "rendah", "sedang", "sekali", "verdict", "unions", "unemployment", "ammunition", "timescale", "tariff", "skop", "sesi", "sastera", "radio","penyakit", "monoplies", "unity", "kredit", "jurutera", "attendance", "divides", "services", "di", "defence", "pay", "million",
    "nanti", "skilled", "quality", "terminal", "allowance", "ayat", "warganegara", "visit", "development", "faktor", "faedah", "journalists", "maknanya", "motokar", "transparency", "panjang", "teres", "promotion", "RM", "trade", "translation", "weapons", "sewa", "medal", "maize", "kusta", "kaki", "taxes", "pagi"
]