titles = [
    "YB Tuan",
    "YB Senator Tuan",
    "Yang Berhormat",
    "YB",
    "YAB",
    "Senator",
    "Tan Sri",
    "Dato' Seri Utama",
    "Dato Seri Utama",
    "Dato' Sri",
    "Dato Sri",
    "Dato' Seri",
    "Dato Seri",
    "Dato' Wira",
    "Dato Wira",
    "Dato'",
    "Dato",
    "Datuk Seri Utama",
    "Datuk Seri Panglima",
    "Datuk Seri",
    "Datuk Wira",
    "Datuk",
    "Haji",
    "Ir",
    "Dr",
    "Puan",
    "Tuan",
    "Tun",
    "Hajah"
]